server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service

  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: catalogo
      port: 27018

queue:
  movie:
    name: NewMovie
  serie:
    name: NewSerie

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info,ratelimiters,metrics
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      series:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled : true
    retry:
      instances:
        series:
          maxAttempts: 3
          waitDuration: 1000
          retryExceptions[0]: feign.FeignException$InternalServerError
