server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movie-service #identificador de la ruta
          uri: lb://movie-service #URL donde se hará el redirect segun el predicado definido
          predicates: #Reglas de analisis de request
            - Path=/movie/** #path de url de request a considerar
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway