server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server

cloud:
  config:
    server:
      git:
        uri: https://github.com/nataliehelm/spring-cloud-config
        default-label: main   //brach en github
        force-pull: true
